CREATE DATABASE HOTEL_MANAGER
GO

USE HOTEL_MANAGER
GO

CREATE TABLE LOAI_PHONG (
	MaLoaiPhong int IDENTITY PRIMARY KEY,
	TenLoaiPhong NVARCHAR(30) NOT NULL DEFAULT N'chua dat ten',
	DonGia MONEY
)
GO

CREATE TABLE PHONG (
	MaPhong INT IDENTITY PRIMARY KEY,
	TenPhong NVARCHAR(30) NOT NULL DEFAULT N'chua dat ten',
	MaLoaiPhong INT NOT NULL,
	GhiChu NVARCHAR(100) DEFAULT N'chua co ghi chu',
	TinhTrangPhong INT NOT NULL DEFAULT 1, -- 1: Có thể cho thuê || 0: Có ng thuê, đang sửa chữa

	FOREIGN KEY (MaLoaiPhong) REFERENCES dbo.LOAI_PHONG(MaLoaiPhong)
)
GO

CREATE TABLE LOAI_KHACHHANG (
	MaLoaiKhachHang INT IDENTITY PRIMARY KEY,
	TenLoaiKhachHang NVARCHAR(30) NOT NULL DEFAULT N'chua dat ten',
)
GO

CREATE TABLE KHACHHANG (
	MaKhachHang INT IDENTITY PRIMARY KEY,
	TenKhachHang NVARCHAR(50) NOT NULL DEFAULT N'chua dat ten',
	MaLoaiKhachHang INT NOT NULL,
	CMND INT,
	DiaChi NVARCHAR(100) DEFAULT N'chua them dia chi',

	FOREIGN KEY (MaLoaiKhachHang) REFERENCES dbo.LOAI_KHACHHANG(MaLoaiKhachHang)
)
GO

CREATE TABLE PHIEUTHUEPHONG (
	MaPT INT IDENTITY PRIMARY KEY,
	MaPhong INT NOT NULL,
	NgayBatDau DATETIME NOT NULL DEFAULT GETDATE(),
	TinhTrangThanhToan INT DEFAULT 0, -- 0: Chưa Thanh Toán || 1: Đã Thanh Toán

	FOREIGN KEY (MaPhong) REFERENCES dbo.PHONG(MaPhong)
)
GO

CREATE TABLE CHITIET_PHIEUTHUE (
	MaCTPT INT IDENTITY PRIMARY KEY,
	MaPT INT NOT NULL,
	MaKhachHang INT NOT NULL

	FOREIGN KEY (MaPT) REFERENCES dbo.PHIEUTHUEPHONG(MaPT),
	FOREIGN KEY (MaKhachHang) REFERENCES dbo.KHACHHANG(MaKhachHang) 
)
GO

CREATE TABLE HOADON (
	MaHD INT IDENTITY PRIMARY KEY,
	TenKhachHang NVARCHAR(50) DEFAULT N'chua ghi ten',
	TriGia FLOAT
)
GO

CREATE TABLE CHITIET_HOADON (
	MaCTHD INT IDENTITY PRIMARY KEY,
	MaHD INT NOT NULL,
	MaPT INT NOT NULL,
	SoNgayThue INT,
	NgayThanhToan DATETIME NOT NULL DEFAULT GETDATE(),
	ThanhTien MONEY,

	FOREIGN KEY (MaHD) REFERENCES dbo.HOADON(MaHD),
	FOREIGN KEY (MaPT) REFERENCES dbo.PHIEUTHUEPHONG(MaPT)
)
GO

CREATE TABLE DOANHTHU (
	MaDT INT IDENTITY PRIMARY KEY,
	Thang INT NOT NULL DEFAULT MONTH(GETDATE()),
	Nam INT NOT NULL DEFAULT YEAR(GETDATE()),
	MaLoaiPhong INT NOT NULL,
	DoanhThu MONEY,
	TyLe FLOAT,

	FOREIGN KEY (MaLoaiPhong) REFERENCES dbo.LOAI_PHONG(MaLoaiPhong)

)
GO

CREATE TABLE THAMSO (
	TenThamSo NVARCHAR(20),
	GiaTri FLOAT,
	--Các Record THAMSO(TenThamSo, GiaTri)

	----KhachToiDa		:  3
	----PhuThu			:  0.25
	----HeSo			:  1.5
)
GO

INSERT INTO dbo.THAMSO( TenThamSo, GiaTri ) VALUES  ( 'KhachToiDa', 3)
INSERT INTO dbo.THAMSO( TenThamSo, GiaTri ) VALUES  ( 'PhuThu', 0.25)
INSERT INTO dbo.THAMSO( TenThamSo, GiaTri ) VALUES  ( 'HeSo', 1.5 )
GO












