CREATE DATABASE HOTEL_MANAGER
GO

USE HOTEL_MANAGER
GO

CREATE TABLE LOAI_PHONG (
	MaLoaiPhong int NOT NULL PRIMARY KEY,
	TenLoaiPhong NVARCHAR(30) NOT NULL DEFAULT N'chua dat ten',
	DonGia MONEY
)
GO

CREATE TABLE PHONG (
	MaPhong INT NOT NULL PRIMARY KEY,
	TenPhong NVARCHAR(30) NOT NULL DEFAULT N'chua dat ten',
	MaLoaiPhong INT NOT NULL,
	GhiChu NVARCHAR(100) DEFAULT N'chua co ghi chu',
	TinhTrangPhong INT NOT NULL DEFAULT 1, -- 1: Có thể cho thuê || 0: Có ng thuê, đang sửa chữa

	FOREIGN KEY (MaLoaiPhong) REFERENCES dbo.LOAI_PHONG(MaLoaiPhong)
)
GO

CREATE TABLE LOAI_KHACHHANG (
	MaLoaiKhachHang INT NOT NULL PRIMARY KEY,
	TenLoaiKhachHang NVARCHAR(30) NOT NULL DEFAULT N'chua dat ten',
)
GO

CREATE TABLE KHACHHANG (
	MaKhachHang INT NOT NULL PRIMARY KEY,
	TenKhachHang NVARCHAR(50) NOT NULL DEFAULT N'chua dat ten',
	MaLoaiKhachHang INT NOT NULL,
	CMND INT,
	DiaChi NVARCHAR(100) DEFAULT N'chua them dia chi',

	FOREIGN KEY (MaLoaiKhachHang) REFERENCES dbo.LOAI_KHACHHANG(MaLoaiKhachHang)
)
GO

CREATE TABLE PHIEUTHUEPHONG (
	MaPT INT NOT NULL PRIMARY KEY,
	MaPhong INT NOT NULL,
	NgayBatDau DATETIME NOT NULL DEFAULT GETDATE(),
	TinhTrangThanhToan INT DEFAULT 0, -- 0: Chưa Thanh Toán || 1: Đã Thanh Toán

	FOREIGN KEY (MaPhong) REFERENCES dbo.PHONG(MaPhong)
)
GO

CREATE TABLE CHITIET_PHIEUTHUE (
	MaCTPT INT NOT NULL PRIMARY KEY,
	MaPT INT NOT NULL,
	MaKhachHang INT NOT NULL

	FOREIGN KEY (MaPT) REFERENCES dbo.PHIEUTHUEPHONG(MaPT),
	FOREIGN KEY (MaKhachHang) REFERENCES dbo.KHACHHANG(MaKhachHang) 
)
GO

CREATE TABLE HOADON (
	MaHD INT NOT NULL PRIMARY KEY,
	TenKhachHang NVARCHAR(50) DEFAULT N'chua ghi ten',
	TriGia FLOAT
)
GO

CREATE TABLE CHITIET_HOADON (
	MaCTHD INT NOT NULL PRIMARY KEY,
	MaHD INT NOT NULL,
	MaPT INT NOT NULL,
	SoNgayThue INT,
	NgayThanhToan DATETIME NOT NULL DEFAULT GETDATE(),
	ThanhTien MONEY,

	FOREIGN KEY (MaHD) REFERENCES dbo.HOADON(MaHD),
	FOREIGN KEY (MaPT) REFERENCES dbo.PHIEUTHUEPHONG(MaPT)
)
GO

CREATE TABLE DOANHTHU (
	MaDT INT NOT NULL PRIMARY KEY,
	Thang INT NOT NULL DEFAULT MONTH(GETDATE()),
	Nam INT NOT NULL DEFAULT YEAR(GETDATE()),
	MaLoaiPhong INT NOT NULL,
	DoanhThu MONEY,
	TyLe FLOAT,

	FOREIGN KEY (MaLoaiPhong) REFERENCES dbo.LOAI_PHONG(MaLoaiPhong)

)
GO

CREATE TABLE THAMSO (
	TenThamSo NVARCHAR(20),
	GiaTri FLOAT,
	--Các Record THAMSO(TenThamSo, GiaTri)

	----KhachToiDa		:  3
	----PhuThu			:  0.25
	----HeSo			:  1.5
)
GO

INSERT INTO dbo.THAMSO( TenThamSo, GiaTri ) VALUES  ( 'KhachToiDa', 3)
INSERT INTO dbo.THAMSO( TenThamSo, GiaTri ) VALUES  ( 'PhuThu', 0.25)
INSERT INTO dbo.THAMSO( TenThamSo, GiaTri ) VALUES  ( 'HeSo', 1.5 )
GO

INSERT INTO dbo.LOAI_PHONG ( MaLoaiPhong, TenLoaiPhong, DonGia )VALUES(1,'A', 150000)
INSERT INTO dbo.LOAI_PHONG ( MaLoaiPhong, TenLoaiPhong, DonGia )VALUES(2,'B', 170000)
INSERT INTO dbo.LOAI_PHONG ( MaLoaiPhong, TenLoaiPhong, DonGia )VALUES(3,'C', 200000)
GO

INSERT INTO dbo.LOAI_KHACHHANG( MaLoaiKhachHang ,TenLoaiKhachHang)VALUES  ( 1,'Nội địa' )
INSERT INTO dbo.LOAI_KHACHHANG( MaLoaiKhachHang ,TenLoaiKhachHang)VALUES  ( 2,'Nước ngoài' )
GO

INSERT INTO dbo.PHONG( MaPhong,TenPhong,MaLoaiPhong,GhiChu,TinhTrangPhong)VALUES(1,'Phòng 1', 1, 'note 1', 1)
INSERT INTO dbo.PHONG( MaPhong,TenPhong,MaLoaiPhong,GhiChu,TinhTrangPhong)VALUES(2,'Phòng 2', 2, 'note 2', 1)
INSERT INTO dbo.PHONG( MaPhong,TenPhong,MaLoaiPhong,GhiChu,TinhTrangPhong)VALUES(3,'Phòng 3', 1, 'note 3', 0)
INSERT INTO dbo.PHONG( MaPhong,TenPhong,MaLoaiPhong,GhiChu,TinhTrangPhong)VALUES(4,'Phòng 4', 3, 'note 4', 1)
GO

